In [1]:
2*2

4

In [2]:
import numpy as np

In [3]:
x = np.array([0, 1, 2, 3])
x

array([0, 1, 2, 3])

In [4]:
w = np.array([[0, 1, 2, 3], [4, 5, 6,7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [5]:
y = np.arange(8).reshape(2, 4)
y

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
print(np.square(x))
print(np.sqrt(x))
print(np.cos(x))

[0 1 4 9]
[0.         1.         1.41421356 1.73205081]
[ 1.          0.54030231 -0.41614684 -0.9899925 ]


In [7]:
print(np.max(x))
print(np.min(x))
print(np.mean(x))
print(np.std(x))

3
0
1.5
1.118033988749895


In [8]:
import pandas as pd

In [9]:
my_array = np.array([['Montgomery', 'Yellohammer State', 52423],
                    ['Sacramento', 'Golden state', 163707],
                    ['Oklamhoma City', 'Sooner state', 69960]])
df = pd.DataFrame(my_array)
df

0                  1       2
0      Montgomery  Yellohammer State   52423
1      Sacramento       Golden state  163707
2  Oklamhoma City       Sooner state   69960

In [10]:
df.columns = ['Capital', 'Nickname', 'Area']
df.index = ['Alabama', 'California', 'Oklahoma']
df

Capital           Nickname    Area
Alabama         Montgomery  Yellohammer State   52423
California      Sacramento       Golden state  163707
Oklahoma    Oklamhoma City       Sooner state   69960

In [11]:
df2 = pd.DataFrame(
    my_array,
    columns=['Capital', 'Nickname', 'Area'],
    index=['Alabama', 'California', 'Oklahoma'])
df2

Capital           Nickname    Area
Alabama         Montgomery  Yellohammer State   52423
California      Sacramento       Golden state  163707
Oklahoma    Oklamhoma City       Sooner state   69960

In [12]:
names = ['George',
         'John',
         'Thomas',
         'James',
         'Andrew',
         'Martin',
         'William',
         'Zachary',
         'Millard',
         'Franklin']

purchases = pd.DataFrame(index=names)

purchases['country'] = ['US', 'CAN', 'CAN', 'US', 'CAN', 'US', 'US', 'US', 'CAN', 'US']
purchases['ad_views'] = [16, 32, 52, 13,  55, 92, 23, 64, 26, 28]
purchases['items_purchased'] = [2, 1, 0, 8, 0, 5, 7, 3, 0, 5]
purchases

country  ad_views  items_purchased
George        US        16                2
John         CAN        32                1
Thomas       CAN        52                0
James         US        13                8
Andrew       CAN        55                0
Martin        US        92                5
William       US        23                7
Zachary       US        64                3
Millard      CAN        26                0
Franklin      US        28                5

In [13]:
purchases['country']

George       US
John        CAN
Thomas      CAN
James        US
Andrew      CAN
Martin       US
William      US
Zachary      US
Millard     CAN
Franklin     US
Name: country, dtype: object

In [14]:
purchases['items_purch_per_ad'] = purchases['items_purchased'] / purchases['ad_views']
purchases

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
John         CAN        32                1            0.031250
Thomas       CAN        52                0            0.000000
James         US        13                8            0.615385
Andrew       CAN        55                0            0.000000
Martin        US        92                5            0.054348
William       US        23                7            0.304348
Zachary       US        64                3            0.046875
Millard      CAN        26                0            0.000000
Franklin      US        28                5            0.178571

In [15]:
purchases['items_purchased'] / purchases['ad_views']

George      0.125000
John        0.031250
Thomas      0.000000
James       0.615385
Andrew      0.000000
Martin      0.054348
William     0.304348
Zachary     0.046875
Millard     0.000000
Franklin    0.178571
dtype: float64

In [16]:
purchases.loc['George']

country                  US
ad_views                 16
items_purchased           2
items_purch_per_ad    0.125
Name: George, dtype: object

In [17]:
purchases.loc[:, 'country']

George       US
John        CAN
Thomas      CAN
James        US
Andrew      CAN
Martin       US
William      US
Zachary      US
Millard     CAN
Franklin     US
Name: country, dtype: object

In [18]:
purchases.loc['George', 'country']

'US'

In [19]:
purchases.iloc[1:3, 1]

John      32
Thomas    52
Name: ad_views, dtype: int64

In [20]:
purchases.loc[lambda df: purchases['items_purchased'] > 1, :]

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
James         US        13                8            0.615385
Martin        US        92                5            0.054348
William       US        23                7            0.304348
Zachary       US        64                3            0.046875
Franklin      US        28                5            0.178571

In [21]:
purchases[purchases['items_purchased'] > 1]

country  ad_views  items_purchased  items_purch_per_ad
George        US        16                2            0.125000
James         US        13                8            0.615385
Martin        US        92                5            0.054348
William       US        23                7            0.304348
Zachary       US        64                3            0.046875
Franklin      US        28                5            0.178571

In [22]:
purchases.groupby('country').aggregate(np.mean)

ad_views  items_purchased  items_purch_per_ad
country                                                
CAN      41.250000             0.25            0.007812
US       39.333333             5.00            0.220754

In [35]:
df = pd.read_csv('data/purchases.csv')
print(df)

  Unnamed: 0 country  ad_views  items_purchased
0     George      US        16                2
1       John     CAN        42                1
2     Thomas     CAN        32                0
3      James      US        13                8
4     Andrew     CAN        63                0
5     Martin      US        19                5
6    William      US        65                7
7    Zachary      US        23                3
8    Millard     CAN        16                0
9   Franklin      US        77                5


In [36]:
df.to_csv('data/find_me.csv')

In [38]:
df = pd.read_json('data/purchases.json')
df

Unnamed: 0 country  ad_views  items_purchased
0     George      US        16                2
1       John     CAN        42                1
2     Thomas     CAN        32                0
3      James      US        13                8
4     Andrew     CAN        63                0
5     Martin      US        19                5
6    William      US        65                7
7    Zachary      US        23                3
8    Millard     CAN        16                0
9   Franklin      US        77                5

In [39]:
df.to_json('data/find_me2.json')